
language: perl
perl:
  - "5.10"

branches:
  only:
    - master

# make sure up-to-date
before_install:
  - perlbrew -f install-cpanm

install:
  - cpanm --quiet --notest --local-lib local --installdeps .

script: HARNESS_IS_VERBOSE=1 prove -v -Ilib -Mlib=local/lib/perl5 t

